version: 2
jobs:
  build:
    docker:
      - image: node:8
    steps:
      - run: apt-get update && apt-get install -y opam
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn --frozen-lockfile
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn build
      - run: yarn test
workflows:
  version: 2
  build:
    jobs:
      - build